In [1]:
#사고 데이터 수집
# 데이터 크롤링을 사용해서 데이터셋을 만들고, 이미지를 학습하는 모델
from icrawler.builtin import GoogleImageCrawler
google_cravier = GoogleImageCrawler(parser_threads=2, downloader_threads=4,
                                   storage={'root_dir': './data'})

google_cravier.crawl(keyword = 'car crash', max_num=500,
                   min_size=(200,200), max_size=(None))

2022-02-14 17:17:55,486 - INFO - icrawler.crawler - start crawling...
2022-02-14 17:17:55,501 - INFO - icrawler.crawler - starting 1 feeder threads...
2022-02-14 17:17:55,501 - INFO - feeder - thread feeder-001 exit
2022-02-14 17:17:55,503 - INFO - icrawler.crawler - starting 2 parser threads...
2022-02-14 17:17:55,504 - INFO - icrawler.crawler - starting 4 downloader threads...
2022-02-14 17:17:56,546 - INFO - parser - parsing result page https://www.google.com/search?q=car+crash&ijn=0&start=0&tbs=&tbm=isch
2022-02-14 17:17:56,595 - INFO - downloader - skip downloading file 000001.jpg
2022-02-14 17:17:56,597 - INFO - downloader - skip downloading file 000002.jpg
2022-02-14 17:17:56,598 - INFO - downloader - skip downloading file 000003.jpg
2022-02-14 17:17:56,599 - INFO - downloader - skip downloading file 000004.jpg
2022-02-14 17:17:56,600 - INFO - downloader - skip downloading file 000005.jpg
2022-02-14 17:17:56,600 - INFO - downloader - skip downloading file 000006.jpg
2022-02-14 1

2022-02-14 17:17:57,379 - INFO - downloader - image #86	https://cdn.abcotvs.com/dip/images/11003449_090621-ktrk-ewn-6am-bbe-dwi-crash-sarah-vid.jpg
2022-02-14 17:17:57,460 - INFO - downloader - image #87	https://www.irishtimes.com/polopoly_fs/1.4128426.1577911509!/image/image.jpg
2022-02-14 17:17:57,784 - INFO - downloader - image #88	https://images.cm.archant.co.uk/resource/blob/8337936/e58216b21e20f2f6a85a0425daa8a52f/image5-data.jpg
2022-02-14 17:17:57,787 - INFO - parser - parsing result page https://www.google.com/search?q=car+crash&ijn=3&start=300&tbs=&tbm=isch
2022-02-14 17:17:57,878 - ERROR - downloader - Response status code 403, file https://gray-kktv-prod.cdn.arcpublishing.com/resizer/lG-EvYGgw2OGjY5jesPBib8jPRg\u003d/800x533/smart/filters:quality(70)/cloudfront-us-east-1.images.arcpublishing.com/gray/6TT73F7ESNHELJGHMBW5XYI3PU.jpg
2022-02-14 17:17:57,986 - INFO - parser - parsing result page https://www.google.com/search?q=car+crash&ijn=4&start=400&tbs=&tbm=isch
2022-02-14 

In [7]:
#수집한 데이터를 이미지 처리 및 train/test set으로 나누는 과정
from PIL import Image
import os, glob
import numpy as np
from sklearn.model_selection import train_test_split

#분류대상 카테고리 선택하기
accident_dir = "./image"
categories = ["Car front crash",
             "Car side crash",
             "Rear and crash",
             "Car broken windsheild",
             "Car scratch",
             "Flat tire",
             "Overturned vehicle"]
nb_classes = len(categories)

#이미지 크기 지정
image_w = 64
image_h = 64
pixels = image_w * image_h * 3

#이미지 데이터 읽어들이기
X = []
Y = []
for idx, cat in enumerate(categories):
    # 레이블 지정
    label = [0 for i in range(nb_classes)]
    label[idx] = 1
    # 이미지
    image_dir = (r"C:\Users\11\Desktop\keras\data")
    files = glob.glob(image_dir+"/*.jpg")    #*는 jpg로 끝나는 모든 파일을 읽어오겠다~
    for i , f in enumerate(files):
        img = Image.open(f)
        img = img.convert("RGB")
        img = img.resize((image_w, image_h))
        data = np.asarray(img)
        X.append(data)
        Y.append(label)
        if i % 10 == 0:
            print(i, "\n", data)

X = np.array(X)
Y = np.array(Y)
# 학습 전용 데이터와 테스트 전용 데이터 구분
X_train, X_test, y_train, y_test = train_test_split(X, Y)
xy = (X_train, X_test, y_train, y_test)

print(">>> data 저장중...")
np.save("./7obj.npy",xy)
print("ok", len(Y))

0 
 [[[100 119 107]
  [ 98 118 106]
  [ 97 115 103]
  ...
  [171 166 163]
  [168 163 160]
  [171 167 164]]

 [[ 94 116 103]
  [ 97 117 105]
  [ 98 117 101]
  ...
  [171 166 163]
  [180 175 171]
  [169 165 160]]

 [[ 91 113  98]
  [ 94 117  97]
  [ 93 116  95]
  ...
  [168 163 158]
  [170 166 153]
  [172 168 159]]

 ...

 [[174 159 152]
  [161 149 137]
  [171 158 146]
  ...
  [ 93  93  99]
  [ 97  96  97]
  [ 76  77  81]]

 [[169 157 148]
  [166 156 150]
  [142 133 121]
  ...
  [142 146 161]
  [142 143 154]
  [127 130 150]]

 [[154 141 137]
  [158 144 140]
  [158 144 138]
  ...
  [133 134 151]
  [142 147 165]
  [143 154 175]]]
10 
 [[[ 52  55  25]
  [ 70  70  38]
  [ 48  50  22]
  ...
  [167 103  83]
  [173 108  88]
  [122  77  66]]

 [[ 51  56  24]
  [ 55  56  29]
  [ 52  53  27]
  ...
  [168 104  84]
  [166 104  85]
  [165 101  81]]

 [[ 44  48  19]
  [ 53  61  25]
  [ 96  94  73]
  ...
  [171 103  82]
  [176 106  83]
  [120  72  61]]

 ...

 [[147 137 142]
  [147 137 143]
  [148 137 

50 
 [[[160 156 128]
  [155 152 124]
  [149 149 118]
  ...
  [119 134  95]
  [126 139 102]
  [117 128  91]]

 [[162 165 126]
  [167 167 133]
  [168 168 135]
  ...
  [121 130  94]
  [130 135 105]
  [113 116  90]]

 [[136 148 103]
  [142 153 108]
  [142 153 109]
  ...
  [162 160 134]
  [152 150 126]
  [153 149 127]]

 ...

 [[ 83  64  57]
  [ 86  67  60]
  [ 87  69  62]
  ...
  [105 112  66]
  [113 116  74]
  [131 129  89]]

 [[102  83  76]
  [ 83  64  57]
  [ 82  65  58]
  ...
  [119 125  80]
  [126 126  86]
  [138 134  99]]

 [[ 95  76  69]
  [ 98  79  72]
  [103  83  76]
  ...
  [124 130  89]
  [128 128  89]
  [140 136 102]]]
60 
 [[[126  74  12]
  [102  29   6]
  [ 94  48   6]
  ...
  [ 23  28  21]
  [ 25  30  19]
  [ 32  41  14]]

 [[122  91   5]
  [105  59   3]
  [ 95  55   5]
  ...
  [ 40  46  21]
  [ 41  52  18]
  [ 67  86  12]]

 [[103  86   6]
  [ 83  75   3]
  [102  83   4]
  ...
  [ 70  77  32]
  [ 72  89  21]
  [ 54  72  17]]

 ...

 [[186 182 189]
  [174 169 176]
  [159 155

10 
 [[[ 52  55  25]
  [ 70  70  38]
  [ 48  50  22]
  ...
  [167 103  83]
  [173 108  88]
  [122  77  66]]

 [[ 51  56  24]
  [ 55  56  29]
  [ 52  53  27]
  ...
  [168 104  84]
  [166 104  85]
  [165 101  81]]

 [[ 44  48  19]
  [ 53  61  25]
  [ 96  94  73]
  ...
  [171 103  82]
  [176 106  83]
  [120  72  61]]

 ...

 [[147 137 142]
  [147 137 143]
  [148 137 143]
  ...
  [168 156 164]
  [166 153 162]
  [169 158 165]]

 [[142 132 138]
  [140 129 134]
  [144 132 136]
  ...
  [163 151 159]
  [160 147 156]
  [163 151 160]]

 [[135 124 128]
  [136 123 127]
  [146 130 131]
  ...
  [161 150 159]
  [156 144 152]
  [174 163 170]]]
20 
 [[[ 87  80  63]
  [ 80  75  59]
  [ 86  80  61]
  ...
  [ 56 131 171]
  [ 56 131 171]
  [ 50 128 168]]

 [[ 84  77  61]
  [ 80  75  57]
  [ 83  78  57]
  ...
  [ 51 128 169]
  [ 54 129 169]
  [ 50 127 167]]

 [[ 81  75  59]
  [ 81  75  57]
  [ 81  76  57]
  ...
  [ 50 126 168]
  [ 52 127 167]
  [ 51 126 166]]

 ...

 [[ 27  26  25]
  [ 28  28  27]
  [ 27  27

60 
 [[[126  74  12]
  [102  29   6]
  [ 94  48   6]
  ...
  [ 23  28  21]
  [ 25  30  19]
  [ 32  41  14]]

 [[122  91   5]
  [105  59   3]
  [ 95  55   5]
  ...
  [ 40  46  21]
  [ 41  52  18]
  [ 67  86  12]]

 [[103  86   6]
  [ 83  75   3]
  [102  83   4]
  ...
  [ 70  77  32]
  [ 72  89  21]
  [ 54  72  17]]

 ...

 [[186 182 189]
  [174 169 176]
  [159 155 162]
  ...
  [143 141 146]
  [159 157 162]
  [165 162 166]]

 [[212 210 213]
  [211 210 216]
  [210 210 218]
  ...
  [139 137 144]
  [158 156 161]
  [197 196 203]]

 [[243 210 168]
  [239 212 178]
  [230 210 188]
  ...
  [164 159 165]
  [173 167 173]
  [187 183 190]]]
70 
 [[[170 161 157]
  [181 172 164]
  [178 169 162]
  ...
  [151 151 149]
  [136 136 135]
  [126 126 125]]

 [[175 166 160]
  [192 183 173]
  [186 181 172]
  ...
  [160 160 160]
  [146 146 146]
  [145 145 145]]

 [[184 175 167]
  [203 200 190]
  [198 199 194]
  ...
  [160 158 158]
  [150 149 150]
  [151 151 151]]

 ...

 [[196 193 178]
  [199 196 178]
  [203 200

30 
 [[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 1  1  3]
  [ 0  0  1]]

 [[ 4  1  2]
  [ 3  1  2]
  [ 1  0  1]
  ...
  [ 0  0  1]
  [ 0  0  2]
  [ 0  0  2]]

 [[10  2  7]
  [12  5  9]
  [ 9  5  7]
  ...
  [ 1  1  3]
  [ 1  1  3]
  [ 1  1  3]]

 ...

 [[27 21 19]
  [32 27 27]
  [39 34 35]
  ...
  [31 22 20]
  [28 19 17]
  [24 15 13]]

 [[22 17 17]
  [29 25 25]
  [37 33 35]
  ...
  [27 18 18]
  [24 16 14]
  [23 15 14]]

 [[21 17 18]
  [30 28 29]
  [32 30 33]
  ...
  [20 14 13]
  [21 15 13]
  [19 12 10]]]
40 
 [[[ 70  77  46]
  [ 66  77  43]
  [ 63  75  37]
  ...
  [ 46  44  37]
  [ 52  49  40]
  [ 54  53  42]]

 [[ 70  83  45]
  [ 60  72  34]
  [ 55  70  30]
  ...
  [ 54  51  41]
  [ 47  41  34]
  [ 52  48  41]]

 [[ 63  76  37]
  [ 67  81  43]
  [ 64  80  37]
  ...
  [ 52  48  37]
  [ 46  41  35]
  [ 55  51  45]]

 ...

 [[ 72  79  81]
  [ 37  49  58]
  [ 31  39  48]
  ...
  [ 35  34  32]
  [ 57  52  47]
  [ 80  73  64]]

 [[ 89 102 103]
  [ 73  80  81]
  [ 59  57  55

C:\Users\11\anaconda3\envs\keras\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [13]:
#모델 선언
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import Activation, Dropout, Flatten, Dense
import numpy as np
import os

#카데토기 저장하기
categories = ["Car front crash",
             "Car side crash",
             "Rear and crash",
             "Car broken windsheild",
             "Car scratch",
             "Flat tire",
             "Overturned vehicle"]
nb_classes = len(categories)

img_w = 64
img_h = 64
X_train, X_test, y_train, y_test = np.load("./7obj.npy", allow_pickle=True)

#데이터 정규화하기(0~1사이로)
X_train = X_train.astype("float") / 256
X_test = X_test.astype("float") / 256
print('X_train shape:', X_train.shape)

#모델 구조 정의
model = Sequential()
model.add(Conv2D(32,(3,3), input_shape = X_train.shape[1:], padding='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3,3), padding='same'))
model.add(Activation('relu'))

X_train shape: (467, 64, 64, 3)
